### ISSUE TITLE
Load from url

### ISSUE THREAD

**Issue by KarnSaheb** [thomaslevesque/XamlAnimatedGif#1]
I seem to be not be able to load gifs from a external url, would be amazing if you could direct me on how to do so.
Also, how do I use the play and stop feature?

Otherwise, this is an amazing library! Congrats!

**Comment by thomaslevesque** [comment]
Sorry, I didn't see your edit until now... there isn't a notification when a comment is edited, so it's better to add a new comment.

Have you been able to solve your problem?

**Comment by thomaslevesque** [comment]
http/https URLs are now supported
