### ISSUE TITLE
Support non-GIF images

### ISSUE THREAD

**Issue by thomaslevesque** [thomaslevesque/XamlAnimatedGif#10]
Currently, setting `AnimationBehavior.SourceUri` (or `SourceStream`) only works with GIF images (animated or not). As a result, you can't use the same XAML code for different kinds of image.

Desired behavior is that if the image is not a GIF, the library should just display the image normally, without trying to animate it.

**Comment by abdhoms** [comment]
Waiting for non-GIF image support. A suggestion...provide UI controls to play/pause GIFs.

Thanks for spending your time on improving this project.
