### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by jenokizm** [thomaslevesque/XamlAnimatedGif#12]
Hi, I have a problem. When you use FlipView for example.
Poor performance, retarding when browsing pictures.
In output console pops up many exceptions ...
You could download my example the link http://1drv.ms/1wQux1m to check in?
![ashampoo_snap_2015 03 03_17h54m43s_001_](https://cloud.githubusercontent.com/assets/11296510/6465158/427c5a32-c1d0-11e4-9e37-2602682451d3.png)

**Comment by thomaslevesque** [comment]
It looks like the images take a long time to download; do you observe the same issues with local images (e.g. images embedded in the app as resources)?

**Comment by jenokizm** [comment]
No, it's not just that. Even if we exclude the GIF and only upload JPG that pops up a bunch of exceptions and the application hangs, as compared with standart control <Image>

**Comment by thomaslevesque** [comment]
The exceptions are normal. The decoder part of the library tries to read the image as GIF, and throws an InvalidSignatureException if it's not a GIF. The exception is caught in a higher layer, and it falls back to just showing the non-animated image as a `BitmapImage`. It wouldn't have a big impact on performance, except that `BitmapImage` doesn't reuse the local cache, so it has to re-download the image... I'll try to make it better, but I can't promise anything.

**Comment by jenokizm** [comment]
+ many "System.IO.EndOfStreamException" в XamlAnimatedGif.DLL

**Comment by jenokizm** [comment]
Tell me then, how can I get the download progress of a large file to show <proggressBar> or <proggressRing> until the picture is displayed

**Comment by jenokizm** [comment]
+ please check 
                        <Image x:Name="ImgGifControl" gif:AnimationBehavior.SourceUri="http://new.donplat.ru/spiderman.gif" />
I have not worked (

**Comment by thomaslevesque** [comment]
> many "System.IO.EndOfStreamException" в XamlAnimatedGif.DLL

I don't see that anywhere in your screenshot, and I didn't see it in my own tests either...

> Tell me then, how can I get the download progress of a large file to show proggressBar or proggressRing until the picture is displayed?

There is no support for that in the library. If you want to see the download progress, download the file yourself and pass its local URL (or stream) to the AnimationBehavior.

**Comment by jenokizm** [comment]
1) Please check work the SourceUri http://new.donplat.ru/spiderman.gif but then I have it it does not appear(
2) how to binding Stream from Custom Class?

**Comment by thomaslevesque** [comment]
> 1) Please check work the SourceUri http://new.donplat.ru/spiderman.gif but then I have it it does not appear(

I don't see any issue with this image. It works exactly as expected...

> 2) how to binding Stream from Custom Class?

What do you mean? Your question is very vague, and anyway it isn't specific to this library; you should ask on StackOverflow or on a forum.
Anyway, I don't recommend using the `SourceStream` property; it's useful in some scenarios, but there are some caveats (e.g. you must keep the stream open while the image is displayed). When possible, you should use the `SourceUri` property instead.

**Comment by jenokizm** [comment]
1) yes exactly
2) ok
3) Then not to follow the stream, you might not realize what a Boolean variable "is loaded"

**Comment by thomaslevesque** [comment]
> 3) Then not to follow the stream, you might not realize what a Boolean variable "is loaded"

Sorry, I don't understand what you're saying...

**Comment by jenokizm** [comment]
I mean something like this https://github.com/thomaslevesque/XamlAnimatedGif/issues/11

**Comment by jenokizm** [comment]
I need something that I can understand the state of the picture. Charged or whether it is already loaded. Depending on this show indeterminate progress bar

**Comment by thomaslevesque** [comment]
As said in #11, I plan on adding this feature. Just subscribe to that issue to know when it's done.
