### ISSUE TITLE
nameof and ?.

### ISSUE THREAD

**Issue by camera-haopeng** [thomaslevesque/XamlAnimatedGif#13]
vs2013 does not seem to support nameof and ?. like this:_cancellationTokenSource?.Cancel();

**Comment by thomaslevesque** [comment]
No, it doesn't. These are C# 6 features, you need VS2015 to build the solution.
But unless you want to modify it, you don't need to build it yourself, you can just get the library via NuGet
________________________________
De : camera-haopeng<mailto:notifications@github.com>
Envoyé : ‎18/‎03/‎2015 16:14
À : thomaslevesque/XamlAnimatedGif<mailto:XamlAnimatedGif@noreply.github.com>
Objet : [XamlAnimatedGif] nameof and ?. (#13)


vs2013 does not seem to support nameof and ?. like this:_cancellationTokenSource?.Cancel();

---
Reply to this email directly or view it on GitHub:
https://github.com/thomaslevesque/XamlAnimatedGif/issues/13

**Comment by camera-haopeng** [comment]
Ok, much thanks!
