### ISSUE TITLE
Some GIFs not displaying properly

### ISSUE THREAD

**Issue by msakdillz** [thomaslevesque/XamlAnimatedGif#14]
When using XamlAnimatedGif the GIF attached has some weird artifacts in it for some reason. 

![enemy_mummy_idle](https://cloud.githubusercontent.com/assets/8201238/8505830/9f9dd64e-21c2-11e5-9b5e-c8c7a0578cba.gif)

**Comment by thomaslevesque** [comment]
Uh. That's weird indeed. I'll look into it.

**Comment by thomaslevesque** [comment]
Fixed in 1.0.0-beta3

**Comment by msakdillz** [comment]
Works perfect , Thanks!
