### ISSUE TITLE
Error	: Unknown attachable member

### ISSUE THREAD

**Issue by alexeygritsenko** [thomaslevesque/XamlAnimatedGif#3]
Error	1	Unknown attachable member 'AnimationBehavior.SourceUri' on element 'Image'	C:\Users\AlexeyW8\documents\visual studio 2013\Projects\XAMLAnimatedGalpha2My\XAMLAnimatedGalpha2My\MainPage.xaml	13	16	XAMLAnimatedGalpha2My

Screenshot here: 
![ashampoo_snap_2015 01 11_19h41m26s_001_](https://cloud.githubusercontent.com/assets/10233486/5695930/e88874b2-99c9-11e4-8f65-0440b07f9a2c.png)

**Comment by thomaslevesque** [comment]
That's weird... The image does appear, so it could be just a glitch in the XAML designer. Do you see this error when you compile, or just when you open the file in the designer? Are you targeting WP 8.1 ?

**Comment by alexeygritsenko** [comment]
The picture is just appeared in the constructor))
But when compiling such a mistake here as in the screenshot ...
Put your library of nuget in most common wp8.1 Project and in addition to adding the code in xaml file nothing else changed.

**Comment by alexeygritsenko** [comment]
If it helps, I packed the project and filled it
ftp: 
http://narkomanpavlik.tv/files/XAMLAnimatedGalpha2My.zip

**Comment by thomaslevesque** [comment]
I can't reproduce it. I created a new WP 8.1 project, added the NuGet package and added an image to my page with the AnimationBehavior.SourceUri property, and it compiles and runs without error.

**Comment by thomaslevesque** [comment]
Just noticed something in your code... the way you declare the XAML namespace is wrong, it's the WPF syntax. In WinRT you should use `xmlns:gif="using:XamlAnimatedGif"`

**Comment by alexeygritsenko** [comment]
Yes, thank you! Now it works.
However, compared with the player on Android, animation and retarding hangs slightly.
But this is the Alpha version. Thank you for a good start.

**Comment by thomaslevesque** [comment]
> However, compared with the player on Android, animation and retarding hangs slightly.

Yes, I'm aware of this. I have a few ideas to improve performance, but I haven't found the time to work on this project lately...

**Comment by alexeygritsenko** [comment]
I like your project, I'm going to use it in one of the student's application to Russia. How can I donate to you in the near times during the following features:
1) increase productivity and remove antsy
2) add the ability to specify the source url from the Internet
?

**Comment by thomaslevesque** [comment]
Hi,

> 1) increase productivity and remove antsy

I don't understand what you mean? Which productivity are you talking about?

> 2) add the ability to specify the source url from the Internet

Well, the fact that remote URLs are not supported is actually a design choice... I want to keep the library as simple as possible, and I don't want to take dependencies on things like HttpClient. Retrieving a remote file using HTTP is beyond the scope of this project, it should be handled at the application level.

I appreciate your willingness to help, but that's not a feature I want to include in the library itself... If you need to display a remote image, just download it to a byte array, create a MemoryStream over the array, and assign it to AnimationBehavior.SourceStream (or download it to a temporary file and use the file URI).

**Comment by alexeygritsenko** [comment]
1) Well, sometimes playing the pictures works not stable as the browser for example...
2) tell me how to assign a code via MemoryStream as a source?
MemoryStream MyStream = ..... ;
myGifControl1.SourceStream = MyStream; //error, SourceStream  not found

**Comment by thomaslevesque** [comment]
> 1) Well, sometimes playing the pictures works not stable as the browser for example...

I'm aware of a performance problem that causes some frames to be skipped, and I'm working to fix it. Did you notice any other problem?

**Comment by alexeygritsenko** [comment]
ok. In my application need to play files of size 2 - 10Mb. I noticed that there is a load on the CPU and RAM, more than it should be. But here I have to make a more detailed testing, as will the time, I will make a report and publish it in a separate topic.

ps Greetings from Russia https://drive.google.com/file/d/0B1xiK3PGIHkBT2c0YkJfN1J4U1E/view?usp=sharing

**Comment by thomaslevesque** [comment]
I just released a new version that fixes some of the performance problems. You should no longer see skipped frames, and the CPU load should be a little lower.

**Comment by alexeygritsenko** [comment]
Yes, It was really good! Thanks for the update! Next week will be back to your project and test as GIF will work with JPG inside FlipView
