### ISSUE TITLE
Looks like last frame may be skipped

### ISSUE THREAD

**Issue by bitsmithsys** [thomaslevesque/XamlAnimatedGif#4]
Thomas, 

I just found this project tonight.  It looks great, however, it looks like there may be an issue with the last frame not being drawn.  In one of my GIFs, it results in the final letter not appearing and there being remnants of the final image when the animation repeats.  In another, the user action isn't completed.  If you'd like, I get make the files available to you privately.  They were exported from Adobe Illustrator by the graphics designer on the team.

**Comment by thomaslevesque** [comment]
Yes, this is a known issue. On large images, sometimes it takes too long to decode and render a frame, and when it happens, the next frame is skipped to keep the timing; this causes visible glitches if the frames are combined with each other. I'm currently working on improving the performance, and I hope it will eventually be fast enough for most images.
If you think your problem is more specific, please provide the images so I can take a look.

**Comment by bitsmithsys** [comment]
Thomas, 

 

Thank you for the quick reply.  The images are somewhat large, 1650 x1064 is one of the largest ones, but they pretty simple and short animations.   I’ve uploaded three of the files to OneDrive.

 

http://1drv.ms/1C4Zthu

 

Step-1_Shoes-Animation.gif – This contains two frames.  I don’t get any motion with this file.

 

Charging –Station-Animation.gif – This contains three frames.  I never see the last frame with the cord plugged in.

 

Wifi-Animation-Typing.gif – I never see the last character typed which is “Y”.  Also,  when it goes back to the first frame on repeat, it doesn’t clear the enlarged screen so there you can see the enlarged screen behind the smaller computer image.

 

All of the animations display properly in IE and there doesn’t appear to be too much processor activity as they are running.

 

I didn’t create the animations myself.  I’ve asked the graphics designer for scaled down versions for testing.  My understanding is that she’s created them in Adobe Illustrator on the Mac.

 

Thanks again and let me know if there’s anything else I can provide to you.

 

>>>DJS>>>

 

David J. Smith

**Comment by thomaslevesque** [comment]
OK, I see the problem. It's indeed a bug, and it's not related to the performance issue I mentioned. Basically, I forgot to adjust the animation duration for the last frame, so the last frame has a duration of 0. I'll fix it ASAP.

**Comment by thomaslevesque** [comment]
Done; your images should now be rendered correctly. I updated the NuGet package as well

**Comment by bitsmithsys** [comment]
They display like a charm here now.  You rock - Thanks!!!
