### ISSUE TITLE
Animated Gif inside a Tooltips? (Question)

### ISSUE THREAD

**Issue by razster** [thomaslevesque/XamlAnimatedGif#6]
May I ask if it is possible to use your code to display an animated GIF inside a tooltip?

i.g. If I hover over a word/button and the tooltip appears, a animated gif will play.

Thanks for any information!

**Comment by thomaslevesque** [comment]
I haven't tried it, but I can't see any reason why it wouldn't work. It should work anywhere you can put an image, since it uses the `Image` control.
