### ISSUE TITLE
This image seems to hang the decoder

### ISSUE THREAD

**Issue by GyleIverson** [thomaslevesque/XamlAnimatedGif#7]
This image gets the decoder into an apparent loop.
![img_81881](https://cloud.githubusercontent.com/assets/7374936/6008007/21de2de6-aad3-11e4-851e-e9268e7600bc.gif)

**Comment by thomaslevesque** [comment]
Thanks for reporting, I'll have a look at it

**Comment by thomaslevesque** [comment]
I can't repro... for me it works fine.
Which platform are you using (Windows Phone, Windows Store app, WPF) ? How are you loading the image?

**Comment by GyleIverson** [comment]
Windows Phone 8.1 Runtime

 

Here is the snippet of code:

 

        protected override async void OnNavigatedTo(NavigationEventArgs e)

        {

            GoogleAnalytics.EasyTracker.GetTracker().SendView("View Image");

 

            if (e.NavigationMode == NavigationMode.New)

            {

                var currentmessageVM = e.Parameter as MessageViewModel;

                var currentmessage = currentmessageVM.Message;

 

                var bitmap = new BitmapImage();

 

                var myself = DatasProvider.Instance.UserData.AccountInfo;

 

                try

                {

                    LoadingPanel.Visibility = Visibility.Visible;

                    var image = await Service.Service.GetMedia(myself.Id, currentmessage.Id);

 

                    IRandomAccessStream randomAccessStream = image.AsRandomAccessStream();

                    await bitmap.SetSourceAsync(randomAccessStream);

                    MyImage.Source = bitmap;

 

                    // we need to figure out what type of image we're being presented

                    image.Seek(0, SeekOrigin.Begin);

                    AnimationBehavior.SetSourceStream(MyImage, image);

 

                    //MyImage.Height = bitmap.PixelHeight;

                    //MyImage.Width = bitmap.PixelWidth;

                    ComputeZoom(bitmap);

 

                    if (_currentTimer != null)

                        _currentTimer.Stop();

 

                    if (!currentmessageVM.Message.Type.StartsWith("Blast"))

                    {

                    var max = Math.Max(currentmessageVM.GetRemainingTime(), currentmessageVM.MessageDuration);

                    _currentTimer = TimerHelper.ToTime(TimeSpan.FromSeconds(max), () =>

                    {

                        try

                        {

                            NavigationServiceExt.GoBack();

                        }

                        catch

                        {

                        }

                    });

                }

                }

                catch (NetworkConnectionException ex)

                {

                    // TODO: see if the carrier and Wi-Fi networks are down

                    ToastProvider.Show(ex.Message);

                }

                catch (Exception ex)

                {

                    ToastProvider.Show("Can't download image");

                    NavigationServiceExt.GoBack();

                }

                finally

                {

                    LoadingPanel.Visibility = Visibility.Collapsed;

                }

            }

 

            Data data = DatasProvider.Instance;

            ApplicationView.GetForCurrentView().IsScreenCaptureEnabled = data.ScreenCaptureAllowed;

        }

**Comment by thomaslevesque** [comment]
Just tried in in the WP demo app; setting the SourceUri works fine, so it must be the way you're setting the image. What kind of stream does `Service.Service.GetMedia` return? It has to be seekable, and kept open as long as the image is displayed. If you can't conveniently do that, copy it to a temporary file and use the file's URI.

**Comment by GyleIverson** [comment]
Thanks for the URI suggestion. I went ahead and wrote the stream to the file system and then GIFs work consistently.
