### ISSUE TITLE
Object Reference not set if setting up programatically

### ISSUE THREAD

**Issue by thedecibelkid** [thomaslevesque/XamlAnimatedGif#8]
basically, it seems I can have only one! If I do the below and try to get the Controller for "ripples" at a later time I get an object reference not set error, if I swap the order in code that one is fine but bubbles is broken

```
            AnimationBehavior.SetAutoStart(bubbles, false);
            AnimationBehavior.SetRepeatBehavior(bubbles, new RepeatBehavior(1));
            AnimationBehavior.SetSourceUri(bubbles, new Uri(@"C:\tdbk\visuals\wc - beat - l.gif"));
            
            AnimationBehavior.SetAutoStart(ripples, false);
            AnimationBehavior.SetRepeatBehavior(ripples, new RepeatBehavior(1));
            AnimationBehavior.SetSourceUri(ripples, new Uri(@"C:\tdbk\visuals\ripples_light.gif"));
       ```

**Comment by thomaslevesque** [comment]
I haven't been able to reproduce the problem on my side. Can you post more code? Or better, provide a minimal project that shows the issue?

**Comment by thomaslevesque** [comment]
Closing this issue now; if you still encounter the problem, please provide the requested details so that I can investigate.
