### ISSUE TITLE
How to use this control in a ListView which contains other normal (png/jpeg) images?

### ISSUE THREAD

**Issue by abdhoms** [thomaslevesque/XamlAnimatedGif#9]
Hello,

This might sound like a dumb question but I can't seem to find a way to use this inside a ListView along with normal images. I don't want to use a converter to do this. 

I get my images from a 3rd party JSON source (example below) and render them into a list.

>    {
>        "ID": "0",
>        "Image": "http://web.com/0image.gif"
>    },
>    {
>        "ID": "1",
>        "Image": "http://web.com/1image.jpg"
>    },

Does this control support rendering of normal images as well? Please give me some ideas on how to do this.

Thanks.

**Comment by thomaslevesque** [comment]
Right now, it only supports GIF images, but I intend to support others. It will just display the static image if it's not a GIF.

**Comment by thomaslevesque** [comment]
In the meanwhile, I suggest you use a ContentControl with a DataTemplateSelector; this way you can pick the template based on the image type.

**Comment by thomaslevesque** [comment]
See #10
